routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('dashboard.index');
});

Auth::routes(["register" => false]);

Route::prefix("dashboard")->namespace("Dashboard")->name("dashboard.")->middleware(["auth:web"])->group(function () {

	Route::get("/", "HomeController@index")->name("index");

    Route::prefix("users")->namespace("User")->name("user.")->group(function(){
        Route::get("/" , "UserController@index")->name("index");
        Route::get("datatable" , "UserController@datatable")->name("datatable");
        Route::get("create" , "UserController@create")->name("create");
        Route::get("{user}/edit" , "UserController@edit")->name("edit");
        Route::get("{user}/details" , "UserController@details")->name("details");
        Route::post("store" , "UserController@store")->name("store");
        Route::get("{user}/user_post_sold_datatable" , "UserController@user_post_sold_datatable")->name("user_post_sold_datatable");
        Route::get("{user}/user_offer_datatable" , "UserController@user_offer_datatable")->name("user_offer_datatable");
        Route::prefix("{user}/update")->name("update.")->group(function(){
            Route::post("user" , "UpdateUserController@updateUser")->name("user");
            Route::post("admin" , "UpdateUserController@updateAdmin")->name("admin");
            Route::post("name" , "UpdateUserController@name")->name("name");
			Route::post("phone_number" , "UpdateUserController@phone_number")->name("phone_number");
			Route::post("is_blocked" , "UpdateUserController@is_blocked")->name("is_blocked");
        });
    });

    Route::prefix("admin")->namespace("User")->name("admin.")->group(function(){
        Route::get("/" , "AdminController@index")->name("index");
        Route::get("datatable" , "AdminController@datatable")->name("datatable");
        Route::get("create" , "AdminController@create")->name("create");
        Route::get("{user}/edit" , "AdminController@edit")->name("edit");
        Route::post("store" , "AdminController@store")->name("store");
    });

    Route::prefix("categories")->namespace("Category")->name("category.")->group(function(){
        Route::get("/" , "CategoryController@index")->name("index");
        Route::get("datatable" , "CategoryController@datatable")->name("datatable");
        Route::get("create" , "CategoryController@create")->name("create");
        Route::get("{category}/edit" , "CategoryController@edit")->name("edit");
        Route::get("{category}/details" , "CategoryController@details")->name("details");
        Route::post("store" , "CategoryController@store")->name("store");
        Route::prefix("{category}/update")->name("update.")->group(function(){
            Route::post("all" , "UpdateCategoryController@all")->name("all");
            Route::post("name" , "UpdateCategoryController@name")->name("name");
            Route::post("is_ship_nationwide" , "UpdateCategoryController@is_ship_nationwide")->name("is_ship_nationwide");
            Route::post("is_valid" , "UpdateCategoryController@is_valid")->name("is_valid");
            Route::post("ordering" , "UpdateCategoryController@ordering")->name("ordering");
        });
        Route::prefix("{category}/box_size")->name("box_size.")->group(function(){
            Route::get("/" , "BoxSizeCategoryController@index")->name("index");
            Route::get("datatable" , "BoxSizeCategoryController@datatable")->name("datatable");
            Route::get("create" , "BoxSizeCategoryController@create")->name("create");
            Route::get("{category_box_size}/edit" , "BoxSizeCategoryController@edit")->name("edit");
            Route::post("store" , "BoxSizeCategoryController@store")->name("store");
            Route::post("{category_box_size}/update" , "BoxSizeCategoryController@update")->name("update");
        });
    });

    Route::prefix("condition")->namespace("Condition")->name("condition.")->group(function(){
        Route::get("/" , "ConditionController@index")->name("index");
        Route::get("datatable" , "ConditionController@datatable")->name("datatable");
        Route::get("create" , "ConditionController@create")->name("create");
        Route::get("{condition}/edit" , "ConditionController@edit")->name("edit");
        Route::post("store" , "ConditionController@store")->name("store");
        Route::prefix("{condition}/update")->name("update.")->group(function(){
            Route::post("all" , "ConditionController@all")->name("all");
            Route::post("name" , "ConditionController@name")->name("name");
            Route::post("is_show" , "ConditionController@is_show")->name("is_show");
            Route::post("ordering" , "ConditionController@ordering")->name("ordering");
        });
    });

    Route::prefix("distance")->namespace("Distance")->name("distance.")->group(function(){
        Route::get("/" , "DistanceController@index")->name("index");
        Route::get("datatable" , "DistanceController@datatable")->name("datatable");
        Route::post("store" , "DistanceController@store")->name("store");
        Route::post("{distance}/delete" , "DistanceController@delete")->name("delete");
        Route::prefix("{distance}/update")->name("update.")->group(function(){
            Route::post("distance" , "DistanceController@distance")->name("distance");
            Route::post("is_show" , "DistanceController@is_show")->name("is_show");
        });
    });

    Route::prefix("post")->namespace("Post")->name("post.")->group(function(){
        Route::get("/" , "PostController@index")->name("index");
        Route::get("{status}/datatable" , "PostController@datatable")->name("datatable");
        Route::get("{user}/user_datatable" , "PostController@user_datatable")->name("user_datatable");
        Route::get("{user}/user_faverate_datatable" , "PostController@user_faverate_datatable")->name("user_faverate_datatable");
        Route::get("{post}/details" , "PostController@details")->name("details");
        Route::get("{post}/faverate_datatable" , "PostController@faverateDatatable")->name("faverate_datatable");
        Route::get("{post}/offer_datatable" , "PostController@offerDatatable")->name("offer_datatable");
        Route::get("{post}/report_data_table" , "PostController@report_data_table")->name("report_data_table");
    });

    Route::prefix("post_sold")->namespace("Post")->name("post_sold.")->group(function(){
        Route::get("/" , "PostSoldController@index")->name("index");
        Route::get("datatable" , "PostSoldController@datatable")->name("datatable");
        Route::get("{post}/details" , "PostSoldController@details")->name("details");
    });

    Route::prefix("post_report")->namespace("Post")->name("post_report.")->group(function(){
        Route::get("/" , "PostReportController@index")->name("index");
        Route::get("datatable" , "PostReportController@datatable")->name("datatable");
        Route::get("{post}/details" , "PostReportController@details")->name("details");
    });

    Route::prefix("user_report")->namespace("User")->name("user_report.")->group(function(){
        Route::get("/" , "UserReportController@index")->name("index");
        Route::get("datatable" , "UserReportController@datatable")->name("datatable");
        Route::get("{user_report}/details" , "UserReportController@details")->name("details");
    });

    Route::prefix("ticket")->namespace("Ticket")->name("ticket.")->group(function(){
        Route::get("/" , "TicketController@index")->name("index");
        Route::get("datatable" , "TicketController@datatable")->name("datatable");
    });

    Route::prefix("settings")->namespace("Setting")->name("settings.")->group(function () {
        Route::get("/", "SettingController@index")->name("index");
        Route::post("/update", "SettingController@update")->name("update");
    });



});

app/Models/Post/PostFaverate.php
<?php

namespace App\Models\Post;

use Illuminate\Database\Eloquent\Model;
use App\User;

class PostFaverate extends Model
{
    protected $fillable = ["user_id" , "post_id"];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function post()
    {
        return $this->belongsTo(Post::class);
    }
}

app/Http/Controllers/Api/Post/PostController.php
<?php

namespace App\Http\Controllers\Api\Post;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Post\Post;
use App\Http\Resources\Post\PostResource;

class PostController extends Controller
{
    public function getPost(Request $request){

        if ($request->has("data")) {
            $request->merge(json_decode($request->data , true));
        }

    	$posts = Post::where(function($q) use ($request){
	    		if ($request->category_id) {
	    			$q->where("category_id" , $request->category_id);
	    		}
    		})
    		->where(function($q) use ($request){
    			if ($request->has("pick_up")) {
    				$q->where("is_ship_nationwide" , 0);
    			}
    		})
    		->where(function($q) use ($request){
    			if ($request->has("shipping")) {
    				$q->where("is_ship_nationwide" , 1);
    			}
    		})
    		->where(function($q) use ($request){
    			if ($request->price_min && $request->price_max) {
    				$q->where("price" , '>' , $request->price_min)
    					->where("price" , '<=' , $request->price_max);
    			}
    		})
    		->where(function($q) use ($request){
    			if ($request->title) {
    				$q->where("title"  , "LIKE", "%$request->title%");
    			}
    		})
    		->where(function($q){
                if(authApi()->check()){
                    $q->where("user_id","<>",authApi()->id());
                }
            })
            ->where(function($q) use ($request){
            	if ($request->has("ordering")) {
            		if ($request->ordering == "newest") {
            			$q->orderBy("created_at", "DESC");
            		}
            		if ($request->ordering == "price_heigh") {
            			$q->orderBy("price", "DESC");
            		}
            		if ($request->ordering == "price_low") {
            			$q->orderBy("price", "ASC");
            		}
            	}
            })
            ->where(function($q) use ($request){
            	if ($request->lat && $request->lon && $request->distance) {
            		$post = Post::where("status" , Post::STATUS_AVAILABLE)->get();
            		$post_distance_id = [];
            		foreach ($post as $p) {
            			$dis = vincentyGreatCircleDistance(
	            			$request->lat , $request->lon , $p->lat , $p->lon
	            		);
	            		if ($dis < $request->distance) {
	            			$post_distance_id[] = $p->id;
	            		}
            		}
            		$q->whereIn("id" , $post_distance_id);
            	}
            })
            ->where("status" , Post::STATUS_AVAILABLE)
            ->skip($request->get("skip", 0))
            ->take($request->get("takeItems",$this->takeItems))
    		->get();

    	return $this->successResponse(PostResource::collection($posts));
    }

    public function show(Post $post){
        return $this->successResponse(new PostResource($post));
    }
}

app/Http/Controllers/Dashboard/Post/PostController.php
<?php

namespace App\Http\Controllers\Dashboard\Post;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;
use App\Models\Post\Post;
use App\User;
use Illuminate\Database\Eloquent\Builder;

class PostController extends Controller
{
    static $viewPath = "dashboard.pages.post.";
    static $route = "dashboard.post.";

    public function __construct()
    {
        $this->middleware('permission:m_post_view')->only(["index", "datatable"]);
    }

    public function index(){
        $status = [
            Post::STATUS_AVAILABLE,
            Post::STATUS_SOLD,
            Post::STATUS_SOLD_OTHER_APP
        ];
       return view(self::$viewPath . "index" , compact("status"));
    }

    public function details(Post $post){
        return view(self::$viewPath . "details" , compact("post"));
    }

    public function datatable($status){
        if ($status == "all") {
			$post = Post::latest()->get();
		}else{
			$post = Post::where("status" , $status)->latest()->get();
		}
        return $this->datatables($post);
    }

    public function user_datatable(User $user){
        return $this->datatables($user->posts);
    }

    public function user_faverate_datatable(User $user){
        $post = Post::whereHas("faverates" , function(Builder $query) use ($user){
            $query->where("user_id" , $user->id);
        })->get();
        return $this->datatables($post);
    }

    private function datatables($post){
        return DataTables::of($post)
        ->editColumn('id' , function($post){
            static $id = 1;
            return $id++;
        })
        ->editColumn('user' , function($post){
             return $post->user->name;
        })
        ->editColumn('title' , function($post){
             return $post->title;
        })
        ->editColumn('category' , function($post){
             return $post->category->name;
        })
        ->editColumn('status' , function($post){
            return __("global.$post->status");
        })
        ->editColumn('created_at' , function($post){
            return $post->created_at->diffForHumans();
        })
        ->addColumn('actions', function ($data) use ($post) {
            $actions = [];
            $actions[] = [
                "name" => trans("global.view"),
                "route" =>  route(self::$route . "details" , $data->id),
                "icon" => "ft-eye"
            ];

            return view("dashboard.datatable.actions", compact('actions', 'data'));
        })
        ->make(true);
    }

    public function faverateDatatable(Post $post){
        $faverate = $post->faverates;
        return DataTables::of($faverate)
            ->editColumn('id' , function($faverate){
                static $id = 1;
                return $id++;
            })
            ->editColumn('avatar', function ($faverate) {
                return view("dashboard.datatable.avatar", [
                    "id" => $faverate->user->id,
                    "url" => route(self::$route . "index"),
                    "avatar" => $faverate->user->avatar,
                ]);
            })
            ->editColumn('name', function ($faverate) {
                return $faverate->user->name;
            })
            ->editColumn('phone_number', function ($faverate) {
                return $faverate->user->phone_number;
            })
            ->editColumn('email', function ($faverate) {
                return $faverate->user->email;
            })
            ->editColumn('created_at', function ($faverate) {
                return $faverate->created_at->diffForHumans();
            })
            ->make(true);
    }

    public function offerDatatable(Post $post){
        $offers = $post->postoffers;
        return DataTables::of($offers)
            ->editColumn('id' , function($offers){
                static $id = 1;
                return $id++;
            })
            ->editColumn('avatar', function ($offers) {
                return view("dashboard.datatable.avatar", [
                    "id" => $offers->user->id,
                    "url" => route(self::$route . "index"),
                    "avatar" => $offers->user->avatar,
                ]);
            })
            ->editColumn('name', function ($offers) {
                return $offers->user->name;
            })
            ->editColumn('price_offer', function ($offers) {
                return $offers->price;
            })
            ->editColumn('status', function ($offers) {
                return $offers->status;
            })
            ->editColumn('created_at', function ($offers) {
                return $offers->created_at->diffForHumans();
            })
            ->make(true);
    }

    public function report_data_table(Post $post){
        $report = $post->postReport;
        return DataTables::of($report)
        ->editColumn('id' , function($report){
            static $id = 1;
            return $id++;
        })
        ->editColumn('user_report' , function($report){
            return $report->user->name;
        })
        ->editColumn('title' , function($report){
             return $report->post->title;
        })
        ->editColumn('category' , function($report){
             return $report->post->category->name;
        })
        ->editColumn('message' , function($report){
             return $report->message;
        })
        ->editColumn('image' , function($report){
            return view("dashboard.datatable.avatar", [
                "id" => $report->id,
                "url" => route(self::$route . "index"),
                "avatar" => $report->image,
            ]);
        })
        ->editColumn('created_at' , function($report){
            return  $report->updated_at->diffForHumans();
        })
        ->addColumn('actions', function ($data) use ($report) {
            $actions = [];
            $actions[] = [
                "name" => trans("global.view"),
                "route" =>  route(self::$route . "details" , $data->post->id),
                "icon" => "ft-eye"
            ];

            return view("dashboard.datatable.actions", compact('actions', 'data'));
        })
        ->make(true);
    }

}

resources/views/dashboard/pages/post/report/details.blade.php
@extends('dashboard.layouts.index')
@section('title')
@lang('global.post_details')
@stop

@section('content')

  <div class="card">
      <div class="card-header">
          <ul class="breadcrumb">
            <li><a href="{{route('dashboard.index')}}">@lang('global.dashboard')</a></li>
            <li><a href="{{route('dashboard.post_report.index')}}">@lang('global.posts_report')</a></li>
            <li>@lang('global.post_details')</li>
          </ul>
        <div class="heading-elements">
          <a href="{{route("dashboard.post_sold.index")}}" class="btn btn-black">
            <i class="ft-arrow-left"></i>
            @lang('global.back')
          </a>
        </div>
      </div>
  </div>
  <div class="row">

    <div class="col-sm-12 col-md-12">
      <div class="card">

        <div class="card-content">
          <div class="card-body">
            <div class="form-body">
                <ul class="nav nav-tabs nav-linetriangle no-hover-bg">

                    <li class="nav-item">
                        <a class="nav-link active" id="setting-tab-all-tab" data-toggle="pill" href="#setting-tab-all" role="tab" aria-controls="setting-tab-general-all">@lang('global.home')</a>

                    </li>

                    @if($post->status != \App\Models\Post\Post::STATUS_AVAILABLE)
                    <li class="nav-item">
                        <a class="nav-link" id="setting-tab-sold-tab" data-toggle="pill" href="#setting-tab-sold" role="tab" aria-controls="setting-tab-general-sold">@lang('global.sold')</a>

                    </li>
                    @endif

                    <li class="nav-item">
                        <a class="nav-link" id="setting-tab-offer-tab" data-toggle="pill" href="#setting-tab-offer" role="tab" aria-controls="setting-tab-general-offer">@lang('global.offer')</a>

                    </li>

                    <li class="nav-item">
                        <a class="nav-link" id="setting-tab-faverate-tab" data-toggle="pill" href="#setting-tab-faverate" role="tab" aria-controls="setting-tab-general-faverate">@lang('global.post_faverates')</a>

                    </li>

                    <li class="nav-item">
                        <a class="nav-link" id="setting-tab-images-tab" data-toggle="pill" href="#setting-tab-images" role="tab" aria-controls="setting-tab-general-images">@lang('global.post_images')</a>

                    </li>

                    <li class="nav-item">
                        <a class="nav-link" id="setting-tab-report-tab" data-toggle="pill" href="#setting-tab-report" role="tab" aria-controls="setting-tab-general-report">@lang('global.post_report')</a>

                    </li>

                </ul>


              <div class="row">

              	<div class="col-12">
                    <div class="tab-content" id="v-pills-tabContent">

          				<div class="tab-pane fade show active" id="setting-tab-all" role="tabpanel" aria-labelledby="setting-tab-all-tab">
          					<br>
          					<br>
                            @include("dashboard.pages.post.includes.home")
          				</div>

                        <div class="tab-pane fade " id="setting-tab-sold" role="tabpanel" aria-labelledby="setting-tab-sold-tab">
          					<br>
          					<br>
                            @include("dashboard.pages.post.includes.sold")
          				</div>

                        <div class="tab-pane fade" id="setting-tab-offer" role="tabpanel" aria-labelledby="setting-tab-offer-tab">
                          <br>
                          <br>
                          @include("dashboard.pages.post.includes.offer")
                        </div>

          				<div class="tab-pane fade" id="setting-tab-faverate" role="tabpanel" aria-labelledby="setting-tab-faverate-tab">
                            <br>
                            <br>
                            @include("dashboard.pages.post.includes.faverate")
          				</div>


                      <div class="tab-pane fade" id="setting-tab-images" role="tabpanel" aria-labelledby="setting-tab-images-tab">
                          <br>
                          <br>
                          @include("dashboard.pages.post.includes.images")
                      </div>


                      <div class="tab-pane fade" id="setting-tab-report" role="tabpanel" aria-labelledby="setting-tab-report-tab">
                        <br>
                        <br>
                        @include("dashboard.pages.post.includes.report")
                      </div>




          			</div>
                </div>


      		  </div>


            </div>
          </div>
        </div>
      </div>
    </div>
   </div>

@stop

@push('js')
<script>

</script>



@endpush

resources/views/dashboard/pages/post/report/index.blade.php
@extends('dashboard.layouts.index')
@section('title')
@lang('global.posts_report')
@stop

@section('content')

<div class="card">
  <div class="card-header">
    <h4 class="card-title">@lang('global.posts_report')</h4>
  </div>
  <div class="card-content">
    <div class="card-body">
      @if (session('success'))
      <div class="alert alert-success" role="alert">
        {{ session('success') }}
      </div>
      @endif
      <table id="dt-post_report" class="table table-striped table-bordered complex-headers">
        <thead>
          <tr>
              <th>#</th>
              <th>@lang('global.user')</th>
              <th>@lang('global.user_report')</th>
              <th>@lang('global.title')</th>
              <th>@lang('global.category')</th>
              <th>@lang('global.message')</th>
              <th>@lang('global.image')</th>
              <th>@lang('global.created_at')</th>
              <th>@lang('global.actions')</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
              <th>#</th>
              <th>@lang('global.user')</th>
              <th>@lang('global.user_report')</th>
              <th>@lang('global.title')</th>
              <th>@lang('global.category')</th>
              <th>@lang('global.message')</th>
              <th>@lang('global.image')</th>
              <th>@lang('global.created_at')</th>
              <th>@lang('global.actions')</th>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>

@stop

@push('js')

<script>
$(function(){
    var table = $("#dt-post_report").DataTable({
        processing: true,
        serverSide: true,
        responsive: {
            details: true
        },
        ajax: '{{route("dashboard.post_report.datatable")}}',
        columns: [
            { data: 'id', name: 'id' },
            { data: 'user', name: 'user' },
            { data: 'user_report', name: 'user_report' },
            { data: 'title', name: 'title' },
            { data: 'category', name: 'category' },
            { data: 'message', name: 'message' },
            { data: 'image', name: 'image' },
            { data: 'created_at', name: 'created_at' },
            { data: 'actions', name: 'actions' },
        ],
        initComplete: function () {
            // Button bloacked
            $("table").on("click","#dt-btn-action",function(){
                var action_id = $(this).attr("data-actionId");
                let url = $(this).data("url");
                $.ajax({
                    url: url,
                    method:"POST",
                    success:function(){
                        table.ajax.reload(null, false);
                    }
                })
            });
            //End Button bloacked
        }
    });
});

</script>

@endpush