routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('dashboard.index');
});

Auth::routes(["register" => false]);

Route::prefix("dashboard")->namespace("Dashboard")->name("dashboard.")->middleware(["auth:web"])->group(function () {

	Route::get("/", "HomeController@index")->name("index");

    Route::prefix("users")->namespace("User")->name("user.")->group(function(){
        Route::get("/" , "UserController@index")->name("index");
        Route::get("datatable" , "UserController@datatable")->name("datatable");
        Route::get("create" , "UserController@create")->name("create");
        Route::get("{user}/edit" , "UserController@edit")->name("edit");
        Route::get("{user}/details" , "UserController@details")->name("details");
        Route::post("store" , "UserController@store")->name("store");
        Route::get("{user}/user_post_sold_datatable" , "UserController@user_post_sold_datatable")->name("user_post_sold_datatable");
        Route::get("{user}/user_offer_datatable" , "UserController@user_offer_datatable")->name("user_offer_datatable");
        Route::prefix("{user}/update")->name("update.")->group(function(){
            Route::post("user" , "UpdateUserController@updateUser")->name("user");
            Route::post("admin" , "UpdateUserController@updateAdmin")->name("admin");
            Route::post("name" , "UpdateUserController@name")->name("name");
			Route::post("phone_number" , "UpdateUserController@phone_number")->name("phone_number");
			Route::post("is_blocked" , "UpdateUserController@is_blocked")->name("is_blocked");
        });
    });

    Route::prefix("admin")->namespace("User")->name("admin.")->group(function(){
        Route::get("/" , "AdminController@index")->name("index");
        Route::get("datatable" , "AdminController@datatable")->name("datatable");
        Route::get("create" , "AdminController@create")->name("create");
        Route::get("{user}/edit" , "AdminController@edit")->name("edit");
        Route::post("store" , "AdminController@store")->name("store");
    });

    Route::prefix("categories")->namespace("Category")->name("category.")->group(function(){
        Route::get("/" , "CategoryController@index")->name("index");
        Route::get("datatable" , "CategoryController@datatable")->name("datatable");
        Route::get("create" , "CategoryController@create")->name("create");
        Route::get("{category}/edit" , "CategoryController@edit")->name("edit");
        Route::get("{category}/details" , "CategoryController@details")->name("details");
        Route::post("store" , "CategoryController@store")->name("store");
        Route::prefix("{category}/update")->name("update.")->group(function(){
            Route::post("all" , "UpdateCategoryController@all")->name("all");
            Route::post("name" , "UpdateCategoryController@name")->name("name");
            Route::post("is_ship_nationwide" , "UpdateCategoryController@is_ship_nationwide")->name("is_ship_nationwide");
            Route::post("is_valid" , "UpdateCategoryController@is_valid")->name("is_valid");
            Route::post("ordering" , "UpdateCategoryController@ordering")->name("ordering");
        });
        Route::prefix("{category}/box_size")->name("box_size.")->group(function(){
            Route::get("/" , "BoxSizeCategoryController@index")->name("index");
            Route::get("datatable" , "BoxSizeCategoryController@datatable")->name("datatable");
            Route::get("create" , "BoxSizeCategoryController@create")->name("create");
            Route::get("{category_box_size}/edit" , "BoxSizeCategoryController@edit")->name("edit");
            Route::post("store" , "BoxSizeCategoryController@store")->name("store");
            Route::post("{category_box_size}/update" , "BoxSizeCategoryController@update")->name("update");
        });
    });

    Route::prefix("condition")->namespace("Condition")->name("condition.")->group(function(){
        Route::get("/" , "ConditionController@index")->name("index");
        Route::get("datatable" , "ConditionController@datatable")->name("datatable");
        Route::get("create" , "ConditionController@create")->name("create");
        Route::get("{condition}/edit" , "ConditionController@edit")->name("edit");
        Route::post("store" , "ConditionController@store")->name("store");
        Route::prefix("{condition}/update")->name("update.")->group(function(){
            Route::post("all" , "ConditionController@all")->name("all");
            Route::post("name" , "ConditionController@name")->name("name");
            Route::post("is_show" , "ConditionController@is_show")->name("is_show");
            Route::post("ordering" , "ConditionController@ordering")->name("ordering");
        });
    });

    Route::prefix("distance")->namespace("Distance")->name("distance.")->group(function(){
        Route::get("/" , "DistanceController@index")->name("index");
        Route::get("datatable" , "DistanceController@datatable")->name("datatable");
        Route::post("store" , "DistanceController@store")->name("store");
        Route::post("{distance}/delete" , "DistanceController@delete")->name("delete");
        Route::prefix("{distance}/update")->name("update.")->group(function(){
            Route::post("distance" , "DistanceController@distance")->name("distance");
            Route::post("is_show" , "DistanceController@is_show")->name("is_show");
        });
    });

    Route::prefix("post")->namespace("Post")->name("post.")->group(function(){
        Route::get("/" , "PostController@index")->name("index");
        Route::get("{status}/datatable" , "PostController@datatable")->name("datatable");
        Route::get("{user}/user_datatable" , "PostController@user_datatable")->name("user_datatable");
        Route::get("{user}/user_faverate_datatable" , "PostController@user_faverate_datatable")->name("user_faverate_datatable");
        Route::get("{post}/details" , "PostController@details")->name("details");
        Route::get("{post}/faverate_datatable" , "PostController@faverateDatatable")->name("faverate_datatable");
        Route::get("{post}/offer_datatable" , "PostController@offerDatatable")->name("offer_datatable");
        Route::get("{post}/report_data_table" , "PostController@report_data_table")->name("report_data_table");
    });

    Route::prefix("post_sold")->namespace("Post")->name("post_sold.")->group(function(){
        Route::get("/" , "PostSoldController@index")->name("index");
        Route::get("datatable" , "PostSoldController@datatable")->name("datatable");
        Route::get("{post}/details" , "PostSoldController@details")->name("details");
    });

    Route::prefix("post_report")->namespace("Post")->name("post_report.")->group(function(){
        Route::get("/" , "PostReportController@index")->name("index");
        Route::get("datatable" , "PostReportController@datatable")->name("datatable");
        Route::get("{post}/details" , "PostReportController@details")->name("details");
    });

    Route::prefix("user_report")->namespace("User")->name("user_report.")->group(function(){
        Route::get("/" , "UserReportController@index")->name("index");
        Route::get("datatable" , "UserReportController@datatable")->name("datatable");
        Route::get("{user_report}/details" , "UserReportController@details")->name("details");
    });

    Route::prefix("ticket")->namespace("Ticket")->name("ticket.")->group(function(){
        Route::get("/" , "TicketController@index")->name("index");
        Route::get("datatable" , "TicketController@datatable")->name("datatable");
    });

    Route::prefix("settings")->namespace("Setting")->name("settings.")->group(function () {
        Route::get("/", "SettingController@index")->name("index");
        Route::post("/update", "SettingController@update")->name("update");
    });



});

app/Http/Controllers/Api/User/UserAddressController.php
<?php

namespace App\Http\Controllers\Api\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Api\User\UserAddressRequest;
use App\Http\Requests\Api\User\UserDistanceRequest;
use App\Models\User\UserAddresse;

class UserAddressController extends Controller
{
    public function show(){
        $addresse =authApi()->user()->addresse;
        return $this->successResponse($addresse , $addresse ? null : __("app.not_found_address"));
    }

    public function store(UserAddressRequest $request){
    	UserAddresse::createOrUpdate($request->all());
    	$user = authApi()->user();

    	return $this->successResponse($user->addresse, __("app.success_save_address"));
    }

    public function storeDistance(UserDistanceRequest $request){
    	UserAddresse::distanceCreateOrUpdate($request->all());
    	$user = authApi()->user();

    	return $this->successResponse($user->addresse, __("app.success_save_distance"));
    }
}

app/Http/Controllers/Api/User/UserController.php
<?php

namespace App\Http\Controllers\Api\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Resources\User\UserInfoRecource;
use App\Http\Resources\User\UsersDataResource;
use App\Models\DeviceToken\DeviceToken;
use App\Http\Requests\Api\User\LogoutRequest;
use App\Http\Requests\Api\User\UserAvatarRequest;
use App\Http\Requests\Api\User\UserCoverImageRequest;
use App\Http\Requests\Api\User\UpdatePasswordRequest;
use App\Http\Requests\Api\User\ValidationProfileRequest;
use Illuminate\Support\Facades\Hash;
use App\User;
use App\Models\User\UserReport;
use App\Models\PhoneVerification\PhoneVerification;
use App\Http\Requests\Api\Auth\CheckCodeRequest;

class UserController extends Controller
{
    public function profile(){
    	return $this->successResponse(
            new UserInfoRecource(authApi()->user())
        );
    }

    public function check_send_email(){
        $user = User::find(authApi()->id());
        if($user->send_email){
            $user->send_email = false;
        }else{
            $user->send_email = true;
        }
        $user->save();
    	return $this->successResponse(new UserInfoRecource($user));
    }

    public function check_send_notification(){
        $user = User::find(authApi()->id());
        if($user->send_notifications){
            $user->send_notifications = false;
        }else{
            $user->send_notifications = true;
        }
        $user->save();
    	return $this->successResponse(new UserInfoRecource($user));
    }

    public function userProfile(User $user){
        return $this->successResponse(
            new UsersDataResource($user)
        );
    }

    public function updateEmail(Request $request){
        $request->validate([
            "email" => "required|email|unique:users,email," . authApi()->id()
        ]);

        $user = authApi()->user();
        $user->email = $request->email;
        $user->save();
        return $this->successResponse(
            new UserInfoRecource($user)
        , __("app.success_updated_email_user"));
    }

    public function updatePhoneNumber(CheckCodeRequest $request){

        if (PhoneVerification::checkCode($request->token, $request->code)) {
            $phoneVerification = PhoneVerification::getByToken($request->token);

            $user = authApi()->user();
            $user->phone_number = $phoneVerification->phone_number;
            $user->save();
            $phoneVerification->delete();
            return $this->successResponse(
                new UserInfoRecource($user)
            , __("app.success_update_phone_number"));
        } else {
            return $this->errorResponse(__("app.invalid_code"), 422);
        }

    }

    public function validation(ValidationProfileRequest $request){
        $user = authApi()->user();
        $user->id_image = upImage($request->image, "users/id_image");
        $user->save();
        return $this->successResponse(
            new UserInfoRecource($user)
        , __("app.success_upload_image_waite_admin_approved_this"));
    }

    public function updatePassword(UpdatePasswordRequest $request)
    {
        $user = authApi()->user();
        if (!Hash::check($request->current_password, $user->password)) {
            return $this->errorResponse(__("app.current_password_not_valid"));
        }
        $user->password = bcrypt($request->password);
        $user->save();
        return $this->successResponse(null, __("app.success_updated_password"));
    }

    public function updateAvatar(UserAvatarRequest $request)
    {
        $user = authApi()->user();
        $user->avatar = upImage($request->avatar, "users/avatar");
        $user->save();
        return $this->successResponse(
            new UserInfoRecource($user)
        , __("app.success_updated_avatar"));
    }

    public function updateCoverImage(UserCoverImageRequest $request)
    {
        $user = authApi()->user();
        $user->cover_image = upImage($request->cover_image, "users/cover_image");
        $user->save();
        return $this->successResponse(
            new UserInfoRecource($user)
        , __("app.success_updated_cover_image"));
    }

    public function logout(LogoutRequest $request){
        authApi()->logout();
        DeviceToken::createOrUpdate([
            "token" => $request->token,
        ]);
        return $this->successResponse(null, "success");
    }

    public function report(Request $request , User $user){
        $report = new UserReport;
        $report->report_id = $user->id;
        $report->user_id = authApi()->id();
        $report->message = $request->message;
        if ($request->has("image")) {
            $report->image = upImage($request->image, "users/report");
        }
        $report->save();
        return $this->successResponse(__("app.success_report"), "success");
    }
}

app/Http/Controllers/Api/User/UserFavoritePostController.php
<?php

namespace App\Http\Controllers\Api\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Post\Post;
use App\Models\Post\PostFaverate;
use App\Http\Resources\Post\PostResource;

class UserFavoritePostController extends Controller
{
    public function faverate(Post $post){

    	$faveratePost = new PostFaverate;
    	$faveratePost->post_id = $post->id;
    	$faveratePost->user_id = authApi()->id();
    	$faveratePost->save();

    	return $this->successResponse(__("app.success_faverate"));
    }

    public function unFaverate(Post $post){

    	$unFaverate = PostFaverate::where("post_id" , $post->id)
    		->where("user_id" , authApi()->id())
    		->delete();

    	return $this->successResponse(__("app.success_un_faverate"));
    }

    public function userFaverate(){

        return $this->successResponse(PostResource::collection(
            Post::whereHas('faverates', function ($query){
                $query->where('user_id', '=',authApi()->id());
            })->get()
        ));
    }
}

app/Http/Controllers/Api/User/UserFollowerController.php
<?php

namespace App\Http\Controllers\Api\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use App\Http\Requests\Api\User\UserFollowerRequest;
use App\Http\Resources\User\UserInfoRecource;
use App\Http\Resources\User\UsersDataResource;
use App\Http\Controllers\Notification\NotificationController;

class UserFollowerController extends Controller
{
    public function follow(UserFollowerRequest $request){

    	$user = User::find($request->user_id);
    	if (! $user) {
    		return $this->errorResponse(__("app.not_found_user_id"));
    	}
    	if ($user->hasFollow($user->id)){
    		return $this->errorResponse(__("app.error_alrady_following"));
    	}
    	User::userFollow($user->id);

        $notification = new NotificationController();
        $notification->sendNotificationsFollowing($user);

    	return $this->successResponse(__("app.success_follow"));
    }

    public function unFollow(UserFollowerRequest $request){

    	$user = User::find($request->user_id);
    	if (! $user) {
    		return $this->errorResponse(__("app.not_found_user_id"));
    	}
    	if (! $user->hasFollow($user->id)){
    		return $this->errorResponse(__("app.error_alrady_un_following"));
    	}
    	User::userUnFollow($user->id);
    	return $this->successResponse(__("app.success_un_follow"));
    }

    public function getFollowers(User $user = null){
        if ($user) {
            $user = User::find($user->id);
        }else{
            $user = User::find(authApi()->id());
        }
        return $this->successResponse(
            UsersDataResource::collection($user->followers()->get())
        );
    }

    public function getFollowing(User $user = null){
        if ($user) {
            $user = User::find($user->id);
        }else{
            $user = User::find(authApi()->id());
        }
        return $this->successResponse(
            UsersDataResource::collection($user->following()->get())
        );
    }


}

app/Http/Controllers/Api/User/UserNotificationController.php
<?php

namespace App\Http\Controllers\Api\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User\Notification;
use App\Http\Resources\Notification\NotificationResource;

class UserNotificationController extends Controller
{
    public function getNotifications(){

    	return $this->successResponse(
    		NotificationResource::collection(
    			Notification::where("user_id" , authApi()->id())
    				->get()
    		)
    	);
    }
}

resources/views/dashboard/pages/user/report/details.blade.php
@extends('dashboard.layouts.index')
@section('title')
@lang('global.user_details')
@stop

@section('content')



<div class="card">
    <div class="card-header">
        <ul class="breadcrumb">
            <li><a href="{{route('dashboard.index')}}">@lang('global.dashboard')</a></li>
            <li><a href="{{route('dashboard.user_report.index')}}">@lang('global.users_report')</a></li>
            <li>@lang('global.user_details')</li>
        </ul>
        <div class="heading-elements">
            <a href="{{route("dashboard.user.index")}}" class="btn btn-black">
                <i class="ft-arrow-left"></i>
                @lang('global.back')
            </a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-12 col-md-12">
        <div class="card">
            <div class="card-content">
                <div class="card-body">
                    <div class="form-body">
                        <ul class="nav nav-tabs nav-linetriangle no-hover-bg">
                            <li class="nav-item">
                                <a class="nav-link active" id="setting-tab-all-tab" data-toggle="pill" href="#setting-tab-all" role="tab" aria-controls="setting-tab-general-all">@lang('global.home')</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" id="setting-tab-user-tab" data-toggle="pill" href="#setting-tab-user" role="tab" aria-controls="setting-tab-general-user">@lang('global.user')</a>
                            </li>
                           <li class="nav-item">
                               <a class="nav-link" id="setting-tab-posts-tab" data-toggle="pill" href="#setting-tab-posts" role="tab" aria-controls="setting-tab-general-posts">@lang('global.posts')</a>
                           </li>
                           <li class="nav-item">
                               <a class="nav-link" id="setting-tab-faverate-tab" data-toggle="pill" href="#setting-tab-faverate" role="tab" aria-controls="setting-tab-general-faverate">@lang('global.post_faverates')</a>
                           </li>
                           <li class="nav-item">
                               <a class="nav-link" id="setting-tab-sold-tab" data-toggle="pill" href="#setting-tab-sold" role="tab" aria-controls="setting-tab-general-sold">@lang('global.user_post_sold')</a>
                           </li>
                           <li class="nav-item">
                               <a class="nav-link" id="setting-tab-offer-tab" data-toggle="pill" href="#setting-tab-offer" role="tab" aria-controls="setting-tab-general-offer">@lang('global.user_offer')</a>
                           </li>
                        </ul>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <div class="tab-content" id="v-pills-tabContent">
                                <div class="tab-pane fade show active" id="setting-tab-all" role="tabpanel" aria-labelledby="setting-tab-all-tab">
                					<br>
                					<br>
                                  @include("dashboard.pages.user.includes.home_report")
                				</div>

                                <div class="tab-pane fade" id="setting-tab-user" role="tabpanel" aria-labelledby="setting-tab-user-tab">
                                  <br>
                                  <br>
                                  @include("dashboard.pages.user.includes.home")
                                </div>


                                  <div class="tab-pane fade" id="setting-tab-posts" role="tabpanel" aria-labelledby="setting-tab-posts-tab">
                                    <br>
                                    <br>
                                    @include("dashboard.pages.user.includes.post")
                                  </div>

                    				<div class="tab-pane fade" id="setting-tab-faverate" role="tabpanel" aria-labelledby="setting-tab-faverate-tab">
                                      <br>
                                      <br>
                                      @include("dashboard.pages.user.includes.faverate")
                    				</div>


                                <div class="tab-pane fade" id="setting-tab-sold" role="tabpanel" aria-labelledby="setting-tab-sold-tab">
                                    <br>
                                    <br>
                                    @include("dashboard.pages.user.includes.sold")
                                </div>


                                <div class="tab-pane fade" id="setting-tab-offer" role="tabpanel" aria-labelledby="setting-tab-offer-tab">
                                  <br>
                                  <br>
                                   @include("dashboard.pages.user.includes.offer")
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@stop

@push('js')
<script>

</script>



@endpush

resources/views/dashboard/pages/user/report/index.blade.php
@extends('dashboard.layouts.index')
@section('title')
@lang('global.users_report')
@stop

@section('content')

<div class="card">
  <div class="card-header">
    <h4 class="card-title">@lang('global.users_report')</h4>
  </div>
  <div class="card-content">
    <div class="card-body">
      @if (session('success'))
      <div class="alert alert-success" role="alert">
        {{ session('success') }}
      </div>
      @endif
      <table id="dt-user_report" class="table table-striped table-bordered complex-headers">
        <thead>
          <tr>
              <th>#</th>
              <th>@lang('global.user_report_to')</th>
              <th>@lang('global.user_report_from')</th>
              <th>@lang('global.message')</th>
              <th>@lang('global.image')</th>
              <th>@lang('global.created_at')</th>
              <th>@lang('global.actions')</th>
          </tr>
        </thead>
        <tfoot>
          <tr>
              <th>#</th>
              <th>@lang('global.user_report_to')</th>
              <th>@lang('global.user_report_from')</th>
              <th>@lang('global.message')</th>
              <th>@lang('global.image')</th>
              <th>@lang('global.created_at')</th>
              <th>@lang('global.actions')</th>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>

@stop

@push('js')

<script>
$(function(){
    var table = $("#dt-user_report").DataTable({
        processing: true,
        serverSide: true,
        responsive: {
            details: true
        },
        ajax: '{{route("dashboard.user_report.datatable")}}',
        columns: [
            { data: 'id', name: 'id' },
            { data: 'user_report_to', name: 'user_report_to' },
            { data: 'user_report_from', name: 'user_report_from' },
            { data: 'message', name: 'message' },
            { data: 'image', name: 'image' },
            { data: 'created_at', name: 'created_at' },
            { data: 'actions', name: 'actions' },
        ],
        initComplete: function () {
            // Button bloacked
            $("table").on("click","#dt-btn-action",function(){
                var action_id = $(this).attr("data-actionId");
                let url = $(this).data("url");
                $.ajax({
                    url: url,
                    method:"POST",
                    success:function(){
                        table.ajax.reload(null, false);
                    }
                })
            });
            //End Button bloacked
        }
    });
});

</script>

@endpush