routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('dashboard.index');
});

Auth::routes(["register" => false]);

Route::prefix("dashboard")->namespace("Dashboard")->name("dashboard.")->middleware(["auth:web"])->group(function () {

	Route::get("/", "HomeController@index")->name("index");

    Route::prefix("users")->namespace("User")->name("user.")->group(function(){
        Route::get("/" , "UserController@index")->name("index");
        Route::get("datatable" , "UserController@datatable")->name("datatable");
        Route::get("create" , "UserController@create")->name("create");
        Route::get("{user}/edit" , "UserController@edit")->name("edit");
        Route::get("{user}/details" , "UserController@details")->name("details");
        Route::post("store" , "UserController@store")->name("store");
        Route::get("{user}/user_post_sold_datatable" , "UserController@user_post_sold_datatable")->name("user_post_sold_datatable");
        Route::get("{user}/user_offer_datatable" , "UserController@user_offer_datatable")->name("user_offer_datatable");
        Route::prefix("{user}/update")->name("update.")->group(function(){
            Route::post("user" , "UpdateUserController@updateUser")->name("user");
            Route::post("admin" , "UpdateUserController@updateAdmin")->name("admin");
            Route::post("name" , "UpdateUserController@name")->name("name");
			Route::post("phone_number" , "UpdateUserController@phone_number")->name("phone_number");
			Route::post("is_blocked" , "UpdateUserController@is_blocked")->name("is_blocked");
        });
    });

    Route::prefix("admin")->namespace("User")->name("admin.")->group(function(){
        Route::get("/" , "AdminController@index")->name("index");
        Route::get("datatable" , "AdminController@datatable")->name("datatable");
        Route::get("create" , "AdminController@create")->name("create");
        Route::get("{user}/edit" , "AdminController@edit")->name("edit");
        Route::post("store" , "AdminController@store")->name("store");
    });

    Route::prefix("categories")->namespace("Category")->name("category.")->group(function(){
        Route::get("/" , "CategoryController@index")->name("index");
        Route::get("datatable" , "CategoryController@datatable")->name("datatable");
        Route::get("create" , "CategoryController@create")->name("create");
        Route::get("{category}/edit" , "CategoryController@edit")->name("edit");
        Route::get("{category}/details" , "CategoryController@details")->name("details");
        Route::post("store" , "CategoryController@store")->name("store");
        Route::prefix("{category}/update")->name("update.")->group(function(){
            Route::post("all" , "UpdateCategoryController@all")->name("all");
            Route::post("name" , "UpdateCategoryController@name")->name("name");
            Route::post("is_ship_nationwide" , "UpdateCategoryController@is_ship_nationwide")->name("is_ship_nationwide");
            Route::post("is_valid" , "UpdateCategoryController@is_valid")->name("is_valid");
            Route::post("ordering" , "UpdateCategoryController@ordering")->name("ordering");
        });
        Route::prefix("{category}/box_size")->name("box_size.")->group(function(){
            Route::get("/" , "BoxSizeCategoryController@index")->name("index");
            Route::get("datatable" , "BoxSizeCategoryController@datatable")->name("datatable");
            Route::get("create" , "BoxSizeCategoryController@create")->name("create");
            Route::get("{category_box_size}/edit" , "BoxSizeCategoryController@edit")->name("edit");
            Route::post("store" , "BoxSizeCategoryController@store")->name("store");
            Route::post("{category_box_size}/update" , "BoxSizeCategoryController@update")->name("update");
        });
    });

    Route::prefix("condition")->namespace("Condition")->name("condition.")->group(function(){
        Route::get("/" , "ConditionController@index")->name("index");
        Route::get("datatable" , "ConditionController@datatable")->name("datatable");
        Route::get("create" , "ConditionController@create")->name("create");
        Route::get("{condition}/edit" , "ConditionController@edit")->name("edit");
        Route::post("store" , "ConditionController@store")->name("store");
        Route::prefix("{condition}/update")->name("update.")->group(function(){
            Route::post("all" , "ConditionController@all")->name("all");
            Route::post("name" , "ConditionController@name")->name("name");
            Route::post("is_show" , "ConditionController@is_show")->name("is_show");
            Route::post("ordering" , "ConditionController@ordering")->name("ordering");
        });
    });

    Route::prefix("distance")->namespace("Distance")->name("distance.")->group(function(){
        Route::get("/" , "DistanceController@index")->name("index");
        Route::get("datatable" , "DistanceController@datatable")->name("datatable");
        Route::post("store" , "DistanceController@store")->name("store");
        Route::post("{distance}/delete" , "DistanceController@delete")->name("delete");
        Route::prefix("{distance}/update")->name("update.")->group(function(){
            Route::post("distance" , "DistanceController@distance")->name("distance");
            Route::post("is_show" , "DistanceController@is_show")->name("is_show");
        });
    });

    Route::prefix("post")->namespace("Post")->name("post.")->group(function(){
        Route::get("/" , "PostController@index")->name("index");
        Route::get("{status}/datatable" , "PostController@datatable")->name("datatable");
        Route::get("{user}/user_datatable" , "PostController@user_datatable")->name("user_datatable");
        Route::get("{user}/user_faverate_datatable" , "PostController@user_faverate_datatable")->name("user_faverate_datatable");
        Route::get("{post}/details" , "PostController@details")->name("details");
        Route::get("{post}/faverate_datatable" , "PostController@faverateDatatable")->name("faverate_datatable");
        Route::get("{post}/offer_datatable" , "PostController@offerDatatable")->name("offer_datatable");
        Route::get("{post}/report_data_table" , "PostController@report_data_table")->name("report_data_table");
    });

    Route::prefix("post_sold")->namespace("Post")->name("post_sold.")->group(function(){
        Route::get("/" , "PostSoldController@index")->name("index");
        Route::get("datatable" , "PostSoldController@datatable")->name("datatable");
        Route::get("{post}/details" , "PostSoldController@details")->name("details");
    });

    Route::prefix("post_report")->namespace("Post")->name("post_report.")->group(function(){
        Route::get("/" , "PostReportController@index")->name("index");
        Route::get("datatable" , "PostReportController@datatable")->name("datatable");
        Route::get("{post}/details" , "PostReportController@details")->name("details");
    });

    Route::prefix("user_report")->namespace("User")->name("user_report.")->group(function(){
        Route::get("/" , "UserReportController@index")->name("index");
        Route::get("datatable" , "UserReportController@datatable")->name("datatable");
        Route::get("{user_report}/details" , "UserReportController@details")->name("details");
    });

    Route::prefix("ticket")->namespace("Ticket")->name("ticket.")->group(function(){
        Route::get("/" , "TicketController@index")->name("index");
        Route::get("datatable" , "TicketController@datatable")->name("datatable");
    });

    Route::prefix("settings")->namespace("Setting")->name("settings.")->group(function () {
        Route::get("/", "SettingController@index")->name("index");
        Route::post("/update", "SettingController@update")->name("update");
    });



});

app/Models/Category/Category.php
<?php

namespace App\Models\Category;

use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;

class Category extends Model implements TranslatableContract
{
    use Translatable;

    /**
     * The relations to eager load on every query.
     *
     * @var array
     */
    protected $with = ['translations'];

    public $translatedAttributes = ['name'];

    public function boxsizes(){
    	return $this->hasMany(CategoryBoxSize::class);
    }

    public function getImageAttribute($image){
        return $image ? url($image) : null;
    }
}

app/Models/Category/CategoryBoxSize.php
<?php

namespace App\Models\Category;

use Illuminate\Database\Eloquent\Model;
use App\Support\Money;

class CategoryBoxSize extends Model
{
    public function getPriceAttribute($price){
        return Money::inDefaultCurrency($price);
    }

    public function category(){
        return $this->belongsTo(Category::class);
    }

    public function getImageAttribute($image){
        return $image ? url($image) : null;
    }
}

app/Models/Category/CategoryTranslation.php
<?php

namespace App\Models\Category;

use Illuminate\Database\Eloquent\Model;

class CategoryTranslation extends Model
{
    public $timestamps = false;

    protected $fillable = ['name'];
}

app/Http/Controllers/Api/Category/CategoryController.php
<?php

namespace App\Http\Controllers\Api\Category;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Resources\Category\CategoryResource;
use App\Http\Resources\Category\CategoryBoxSizeResource;
use App\Models\Category\Category;
use App\Models\Category\CategoryBoxSize;

class CategoryController extends Controller
{
    public function all(){
    	return $this->successResponse(
    		CategoryResource::collection(
    			Category::where("is_valid" , 1)
    			->orderBy("ordering", "ASC")
    			->get()
    		)
    	);
    }

    public function categoryBoxSize(Category $category){
    	return $this->successResponse(
    		CategoryBoxSizeResource::collection(
    			CategoryBoxSize::where("category_id" , $category->id)
    			->orderBy("size", "ASC")
    			->get()
    		)
    	);
    }

}

app/Http/Controllers/Dashboard/Category/BoxSizeCategoryController.php
<?php

namespace App\Http\Controllers\Dashboard\Category;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category\Category;
use App\Models\Category\CategoryBoxSize;
use Yajra\DataTables\Facades\DataTables;
use App\Http\Requests\Dashboard\BoxSize\BoxSizeRequest;

class BoxSizeCategoryController extends Controller
{
    static $viewPath = "dashboard.pages.box_size.";
    static $route = "dashboard.category.box_size.";

    public function __construct()
    {
        $this->middleware('permission:m_category_box_size_view')->only(["index", "datatable"]);
        $this->middleware('permission:m_category_box_size_create')->only(["create", "store"]);
        $this->middleware('permission:m_category_box_size_edit')->only(["edit"]);
    }

    public function index(Category $category){
        return view(self::$viewPath . "index" , compact("category"));
    }

    public function create(Category $category){
        return view(self::$viewPath . "create" , compact("category"));
    }

    public function store(BoxSizeRequest $request , Category $category){
        $box = new CategoryBoxSize;
        $box->category_id = $category->id;
        $box->size = $request->size;
        $box->unit = $request->unit;
        $box->price = $request->price;
        if ($request->has("image")) {
            $box->image = upImage($request->file("image"), "box_size/image");
        }
        $box->save();
        return redirect()->route(self::$route . "index" , $category->id);
    }

    public function edit(Category $category , CategoryBoxSize $category_box_size){
        return view(self::$viewPath . "edit" , compact("category_box_size"));
    }

    public function update(BoxSizeRequest $request  , Category $category , CategoryBoxSize $category_box_size){
        $box = CategoryBoxSize::find($category_box_size->id);
        $box->category_id = $category->id;
        $box->size = $request->size;
        $box->unit = $request->unit;
        $box->price = $request->price;
        if ($request->has("image")) {
            $box->image = upImage($request->file("image"), "box_size/image");
        }
        $box->save();
        return redirect()->route(self::$route . "index" , $category->id);
    }

    public function datatable(Category $category){
        $box = CategoryBoxSize::where("category_id" , $category->id)->latest()->get();
        $admin = auth()->user();
        return DataTables::of($box)
            ->editColumn('id', function ($box) {
                static $id = 1;
                return $id++;
            })
            ->editColumn('image', function ($box) {
                return view("dashboard.datatable.avatar", [
                    "id" => $box->id,
                    "url" => route(self::$route . "index" , $box->category_id),
                    "avatar" => $box->image,
                ]);
            })
            ->editColumn('category_name', function ($box) {
                return $box->category->name;
            })
            ->editColumn('size', function ($box){
                return $box->size;
            })
            ->editColumn('unit', function ($box){
                return $box->unit;
            })
            ->editColumn('price', function ($box)  {
                return $box->price;
            })
            ->editColumn('created_at', function ($box) {
                return $box->created_at->diffForHumans();
            })
            ->addColumn('actions', function ($data) use ($admin) {
                $actions = [];
                if ($admin->can("m_category_box_size_edit")) {
                    $actions[] = [
                        "name" => trans("global.edit"),
                        "route" =>  route(self::$route . "edit", [ "category" => $data->category_id , "category_box_size" => $data->id]),
                        "icon" => "ft-edit"
                    ];
                }
                if (sizeof($actions) < 1) {
                    return __("global.not_have_permissions");
                }
                return view("dashboard.datatable.actions", compact('actions', 'data'));
            })
            ->make(true);
    }
}

app/Http/Controllers/Dashboard/Category/UpdateCategoryController.php
<?php

namespace App\Http\Controllers\Dashboard\Category;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category\Category;
use App\Http\Requests\Dashboard\Category\CreateCategoryRequest;

class UpdateCategoryController extends Controller
{

    public function all (Request $request , Category $category){
        $request->validate([
            "name" => "required",
            "ordering" => "required"
        ]);
        $category->name = $request->name;
        $category->ordering = $request->ordering;
        if ($request->has("image")) {
            $category->image = upImage($request->file("image"), "category/image");
        }
        $category->is_valid = $request->get("is_valid" , 0);
        $category->is_ship_nationwide = $request->get("is_ship_nationwide" , 0);
        $category->save();

        return redirect()->route("dashboard.category." . "index");
    }

    public function is_ship_nationwide(Category $category){
    	if ($category->is_ship_nationwide == 1) {
    		$category->is_ship_nationwide = 0;
    	}else{
    		$category->is_ship_nationwide = 1;
    	}
    	$category->save();

    	return $this->successResponse(null, "success_button_approved");
    }

    public function is_valid(Category $category){
    	if ($category->is_valid == 1) {
    		$category->is_valid = 0;
    	}else{
    		$category->is_valid = 1;
    	}
    	$category->save();

    	return $this->successResponse(null, "success_button_approved");
    }

    public function name(Category $category , Request $request){
    	$category->name = $request->data;
    	$category->save();

    	return $this->successResponse(null, $category->name);
    }

    public function ordering(Category $category , Request $request){
        $categoryController = new CategoryController();
        if ($categoryController->swapOrdering($request->data)) {
            $category->ordering = $request->data;
        	$category->save();
        }
    	return $this->successResponse(null, $category->ordering);
    }
}

resources/views/dashboard/pages/category/create.blade.php
@extends('dashboard.layouts.index')
@section('title')
@lang('global.users')
@endsection

@section('content')
<form class="form" id="form" enctype="multipart/form-data" action="{{route("dashboard.category.store")}}" novalidate method="POST">
    @csrf
    <div class="card">
        <div class="card-header">
            <ul class="breadcrumb">
              <li><a href="{{route('dashboard.index')}}">@lang('global.dashboard')</a></li>
              <li><a href="{{route('dashboard.category.index')}}">@lang('global.categories')</a></li>
              <li>@lang('global.create_category')</li>
            </ul>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="card">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="form-body">
                                <div class="row">

                                    <div class="form-group form-control-sm col-md-6 mb-0">
                                        <div class="form-group form-control-sm col-md-12 mb-0">
                                            <label for="name">@lang('global.name')</label>
                                            <input type="text" id="name" class="form-control form-control-sm @error('name') is-invalid @enderror" placeholder="@lang('global.name')" required value="{{old("name")}}" name="name">
                                            @error('name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>

                                        <div class="form-group form-control-sm col-md-12 mb-0">
                                            <label for="ordering">@lang('global.ordering')</label>
                                            <input type="number" id="ordering" class="form-control form-control-sm @error('ordering') is-invalid @enderror" placeholder="@lang('global.ordering')" required value="{{old("ordering")}}" name="ordering">
                                            @error('ordering')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>

                                        <div class="form-group form-control-sm col-md-12 mb-0">
                                            <input  type="checkbox"  id="is_ship_nationwide" value="1" name="is_ship_nationwide">
                                            <label for="is_ship_nationwide">@lang('global.is_ship_nationwide')</label>
                                        </div>

                                        <div class="form-group form-control-sm col-md-12 mb-0">
                                            <input  type="checkbox"  id="is_valid" value="1" name="is_valid" checked>
                                            <label for="is_valid">@lang('global.is_valid')</label>
                                        </div>

                                    </div>

                                    <div class="form-check form-control-sm col-md-6 mb-0">
                                        <div class="update-avatar-container">
                                            <label for="name">@lang('global.image')</label>
                                            <div>
                                                <img  style="width:200px; height: 100px;" id="img-image" src="{{ isset($service->image) ?$service->image:asset('images-app/image-not-found.png')}}">
                                                <div id="div_image-model-service" class="modal-create">
                                                    <div class="modal-content-create">
                                                        <div class="modal-body-create">
                                                            <img style="display:block; width:100%; height:100%;object-fit: cover;" id="img-image-model" src="{{ isset($service->image) ?$service->image:asset('images-app/image-not-found.png')}}">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <button type="button" id="btn-select-avatar" class="btn btn-primary  btn-sm">
                                                <i class="ft-image"></i> @lang('global.select_image')
                                            </button>
                                            <input name="image" type="file" id="file-avatar">
                                        </div>
                                    </div>

                                    <div class="form-group form-control-sm col-md-12 mb-0">
                                        <a href="{{route("dashboard.category.store")}}" onclick="event.preventDefault();document.getElementById('form').submit();" class="btn btn-info btn-sm">
                                          <i class="ft-save"></i>
                                          @lang('global.save')
                                        </a>
                                    </div>


                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection

@push('js')
<script>
  $("#btn-select-avatar").on("click",function(){
        $("#file-avatar").click();
        $("#file-avatar").change(function(event){
          var fullPath =URL.createObjectURL(event.target.files[0])
          $("#img-image").attr("src",fullPath);
          $("#img-image-model").attr("src",fullPath);
        });
      });

    var modal = document.getElementById("div_image-model-service");
     var img = document.getElementById("img-image");

     img.onclick = function() {
      modal.style.display = "block";
     }

     window.onclick = function(event) {
        if (event.target == modal) {
          modal.style.display = "none";
        }
      }
</script>
@endpush

resources/views/dashboard/pages/category/edit.blade.php
@extends('dashboard.layouts.index')
@section('title')
@lang('global.users')
@endsection

@section('content')
<form class="form" id="form" enctype="multipart/form-data" action="{{route("dashboard.category.update.all" , $category->id)}}" novalidate method="POST">
    @csrf
    <div class="card">
        <div class="card-header">
            <ul class="breadcrumb">
              <li><a href="{{route('dashboard.index')}}">@lang('global.dashboard')</a></li>
              <li><a href="{{route('dashboard.category.index')}}">@lang('global.categories')</a></li>
              <li>@lang('global.edit_category')</li>
            </ul>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="card">
                    <div class="card-content">
                        <div class="card-body">
                            <div class="form-body">
                                <div class="row">

                                    <div class="form-group form-control-sm col-md-6 mb-0">
                                        <div class="form-group form-control-sm col-md-12 mb-0">
                                            <label for="name">@lang('global.name')</label>
                                            <input type="text" id="name" class="form-control form-control-sm @error('name') is-invalid @enderror" placeholder="@lang('global.name')" required value="{{$category->name}}" name="name">
                                            @error('name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>

                                        <div class="form-group form-control-sm col-md-12 mb-0">
                                            <label for="ordering">@lang('global.ordering')</label>
                                            <input type="number" id="ordering" class="form-control form-control-sm @error('ordering') is-invalid @enderror" placeholder="@lang('global.ordering')" required value="{{$category->ordering}}" name="ordering">
                                            @error('ordering')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>

                                        <div class="form-group form-control-sm col-md-12 mb-0">
                                            <input  type="checkbox"  id="is_ship_nationwide" value="1" name="is_ship_nationwide" @if($category->is_ship_nationwide == 1) checked @endif>
                                            <label for="is_ship_nationwide">@lang('global.is_ship_nationwide')</label>
                                        </div>

                                        <div class="form-group form-control-sm col-md-12 mb-0">
                                            <input  type="checkbox"  id="is_valid" value="1" name="is_valid" @if($category->is_valid == 1) checked @endif>
                                            <label for="is_valid">@lang('global.is_valid')</label>
                                        </div>

                                    </div>

                                    <div class="form-check form-control-sm col-md-6 mb-0">
                                        <div class="update-avatar-container">
                                            <label for="name">@lang('global.image')</label>
                                            <div>
                                                <img  style="width:200px; height: 100px;" id="img-image" src="{{ isset($category->image) ?$category->image:asset('images-app/image-not-found.png')}}">
                                                <div id="div_image-model-service" class="modal-create">
                                                    <div class="modal-content-create">
                                                        <div class="modal-body-create">
                                                            <img style="display:block; width:100%; height:100%;object-fit: cover;" id="img-image-model" src="{{ isset($category->image) ?$category->image:asset('images-app/image-not-found.png')}}">
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <button type="button" id="btn-select-avatar" class="btn btn-primary  btn-sm">
                                                <i class="ft-image"></i> @lang('global.select_image')
                                            </button>
                                            <input name="image" type="file" id="file-avatar">
                                        </div>
                                    </div>

                                    <div class="form-group form-control-sm col-md-12 mb-0">
                                        <a href="{{route("dashboard.category.update.all" , $category->id)}}" onclick="event.preventDefault();document.getElementById('form').submit();" class="btn btn-info btn-sm">
                                          <i class="ft-save"></i>
                                          @lang('global.save')
                                        </a>
                                    </div>


                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@endsection

@push('js')
<script>
  $("#btn-select-avatar").on("click",function(){
        $("#file-avatar").click();
        $("#file-avatar").change(function(event){
          var fullPath =URL.createObjectURL(event.target.files[0])
          $("#img-image").attr("src",fullPath);
          $("#img-image-model").attr("src",fullPath);
        });
      });

    var modal = document.getElementById("div_image-model-service");
     var img = document.getElementById("img-image");

     img.onclick = function() {
      modal.style.display = "block";
     }

     window.onclick = function(event) {
        if (event.target == modal) {
          modal.style.display = "none";
        }
      }
</script>
@endpush